version: "3"

services:
  spotter-db:
    image: postgres
    container_name: spotter-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotter
    volumes:
      - db-data:/var/lib/postgresql/data

  spotter:
    image: spotter:latest
    container_name: spotter
    depends_on:
      - spotter-db
    restart: always
    ports:
      - 4000:4000
    environment:
      - CONFIG=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint: sh -c "spotter migrate up && spotter run service"

volumes:
  db-data:
