// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "c554ba3d3bacf8667f7a4d870c36b4b2"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"fc22acac886db0c7687f3b237ceb0db2": "1f8b08000000000000ffb496cf6edb3e0cc7ef7e0adedae09702bfeddaeb5e61e740b1688f982c79129d2c7bfac192ec5ab69c2803ea532b7e45521ffe69dfdee0bf8e5a2b18e17b5fd516c79f589c15c2e0d0baeab502002009e13b53ebd09250477fae4587fe9cf1370368c3a007a540622306c5f0f212746eb041fa40879d2095f13768fa3560d0f4c2b9abb172a509466b544888344326d0d7203b0b25748d008d3282b7b2ff63da42097b8347b2de5237ea7ee20d5e491eaac37b95b26cad19fa0dcc2d4f268ef94704bba424bada52cf64f403a5c20baae8d353d928bf943e83a9cbf4c4e615feb5276f9f2db0fad2b23916964fa37b1fc3b1e87ab812fff0bfc21fa37175430e56f8c7c3e2c6dd18ebe785d3c658a45687d329f103586cd0a2aed1c5daf92b60344854c808b570b590b865541bdd90ed7c7213aa71949ee2e141fb1b8517e498004042e32ebf98264a381bb3719e4498fba411ca6106667cde714efbe8f3c9118ed204b05f343b7c332ea620898fd099c545ba1826dd960ce4ad9fe631ae941250712f5ca866ea567e1f157eb5008ae2ed2e85a76ea3966104cbbaa874a80285e28a678b85f7262925184a3b6af614126b92e87dccadff7cafcf713ea9cd3ffc2f9dc4c62d66e7839e923f3f33c23d3ef3fade13e481cccbf37378fce36e5efe87f3cd5c7525ade9977026f5fbd212fde64c71d3e44cc9eacf2aa6f2edd8306f5916f143f0370000ffffce4e2c2cbc090000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "fc22acac886db0c7687f3b237ceb0db2"})
	}()
	return nil
}()
