// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "c554ba3d3bacf8667f7a4d870c36b4b2"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"fc22acac886db0c7687f3b237ceb0db2": "1f8b08000000000000ffb496cd6edb300cc7ef7e0adeda6029b0eddaeb5e61e740b1688f982c79129d2c7bfac192ec59b69c2803ea532bfe45523f7eb46f6ff0a9a3d60a46f8de57b5c5f1271667853038b4ae7aad00004842f8ced43ab424d4d19f6bd1a13f67fccd00da30e8412990d8884131bcbc049d1b6c903ed061274865fc0d9a7e0d1834bd70ee6aac5c6982d11a151222cd9009f435c8ce42095d23406734deb6b2cf316da184bdc123596fa91b753ff106af240fd5e1bd4a59b6d60cfd06e6962713c7fc23825d52125d6da96732fa8152e10555f4e9a96c945f4a9fc1d4657a62f30affda93b7cf16587d69d91c0bcba7d1bd8fe158743d5c897ff85fe18fd1b8ba21072bfce36171e36e8cf5f3c269632c52abc3e994f8012c366851d7e862edfc15301a242a64845ab85a48dc32aa8d6ec8763eb909d5384a4ff1f0a0fd8dc20b724c0020a171975f4c13259c8dd9384f22cc7dd208e53003333eef38a77df4f9e408476902d82f9a1dbe19175390c447e8cce2225d0c936e4b06f2d64ff318574a09a8b8172e5433752bbf8f0abf5a0045f17697c253b751cb3082655d543a54814271c5b3c5c27b9394120ca51d357b0a893549f43ee6d67fbed7e7381fd4e6fffc2f9dc4c62d66e7839e923f3f33c23d3ef3fade13e481cccbf36378fce76e5efe87f3cd5c7525ade9977026f5fbd212fde64c71d3e44cc9eacf2aa6f2edd8306f59167116fc0d0000ffffa18a7f8fbb090000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "fc22acac886db0c7687f3b237ceb0db2"})
	}()
	return nil
}()
